---
- name: Install nginx
  sudo: yes
  yum: name=nginx state=present

- name: Copy nginx configuration
  sudo: yes
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
